### ISSUE TITLE
HA 2023.4 (beta) no longer works with entities calendar

### ISSUE THREAD

**Issue by gateriderz** [gadgetchnnel/entities_calendar#16]
Home Assistant Core: 2023.4.0b2
Entities_Calendar: 0.0.9
Breaking Change: https://github.com/home-assistant/core/pull/89533

Since the upgrade of HA 2023.4.0, the calendar update fails when end date is not specified or the same as start.

```
Update for calendar.holidays fails
Update for calendar.vacations fails
Update for calendar.other_events fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 178, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 270, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2023-04-04 20:00:00-04:00, 2023-04-04 20:00:00-04:00)

```

I was able to temporarily fix this issue by modifying the logic:

```
    async def async_get_events(self, hass, start_date, end_date):
...
            if start and not entity[CONF_END_TIME]:
                # If there is a start time and no end time options are defined
                # also use the start time as the end time
                end = start + timedelta(days=1)  <<<<<<=================
            else:
                end = _get_date(entity[CONF_END_TIME], state_object)

            # If start time and end time are the same
            if end == start:
                end = start + timedelta(days=1)  <<<<<<=================

...
```

**Comment by vlad36N** [comment]
After update to HA 2023.4.0
Entities_Calendar: 0.0.9
Added temporarily fix by [gateriderz](https://github.com/gateriderz), but still getting error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 178, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 275, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2021-04-07 00:00:00-04:00, 2021-04-07 00:00:00-04:00)

**Comment by gadgetchnnel** [comment]
Can you post your config, and an example of what the state of the entity looks like so I can try too reproduce this?
I'm not seeing that error myself, so this will help with identifying the issue.

**Comment by vlad36N** [comment]
Hi,

In configuration.yaml I have:

`calendar: !include include/calendar.yaml`

In calendar.yaml have a lot, but will give you few

```
- platform: entities_calendar
    calendars:
      - name: Medicine
        entities:
          - entity: sensor.event_medicine
            all_day: true
          - entity: sensor.event_medicine_1
            all_day: true
      - name: Appointments
        entities:
          - entity: sensor.event_appointments_ct
          - entity: sensor.event_appointments_echo
            all_day: false
            start_time:
              timestamp_attribute: start_time
            end_time:
              timestamp_attribute: end_time
      - name: Vacation
        entities:
          - entity: sensor.event_vacation_vlad_inna
            all_day: true
          - entity: sensor.event_vacation_vlad_inna_1
            all_day: true
      - name: Classes
        entities:
          - entity: sensor.event_classes_sql
            all_day: false
            start_time:
              timestamp_attribute: start_time
            end_time:
              timestamp_attribute: end_time
          - entity: sensor.event_classes_sql_1
            all_day: false
            start_time:
              timestamp_attribute: start_time
            end_time:
              timestamp_attribute: end_time
```

Have events.yaml file in located in sensor directory

```
  - platform: template
    sensors:
      event_medicine:
        friendly_name: "Vlad vitamin D"
        value_template: "{{ as_timestamp('2021-04-07') | timestamp_local }}"
        device_class: "timestamp"
      event_medicine_1:
        friendly_name: "Vlad vitamin D"
        value_template: "{{ as_timestamp('2021-04-14') | timestamp_local }}"
        device_class: "timestamp"
      event_appointments_ct:
        friendly_name: "Vlad Lenox Hill CT"
        value_template: "{{ as_timestamp('2021-04-03 08:00:00') | timestamp_local }}"
        device_class: "timestamp"
        attribute_templates:
          start_time: '2021-04-03 08:00:00-04:00'
          end_time: '2021-04-03 09:00:00-04:00'
      event_appointments_echo:
        friendly_name: "Vlad Lenox Hill Echo"
        value_template: "{{ as_timestamp('2021-04-09 11:25:00') | timestamp_local }}"
        device_class: "timestamp"
        attribute_templates:
          start_time: '2021-04-09 11:25:00-04:00'
          end_time: '2021-04-09 12:25:00-04:00'
      event_vacation_vlad_inna:
        friendly_name: "Vlad Inna Vacation"
        value_template: "{{ as_timestamp('2021-06-14') | timestamp_local }}"
        device_class: "timestamp"
      event_vacation_vlad_inna_1:
        friendly_name: "Vlad Inna Vacation"
        value_template: "{{ as_timestamp('2021-06-15') | timestamp_local }}"
        device_class: "timestamp"
      event_classes_sql:
        friendly_name: "SQL Class"
        value_template: "{{ as_timestamp('2021-12-12 13:00:00') | timestamp_local }}"
        device_class: "timestamp"
        attribute_templates:
          start_time: '2021-12-12 13:00:00-05:00'
          end_time: '2021-12-12 15:30:00-05:00'
      event_classes_sql_1:
        friendly_name: "SQL Class"
        value_template: "{{ as_timestamp('2021-12-19 13:00:00') | timestamp_local }}"
        device_class: "timestamp"
        attribute_templates:
          start_time: '2021-12-19 13:00:00-05:00'
          end_time: '2021-12-19 15:30:00-05:00'
```

![calendar](https://user-images.githubusercontent.com/30022288/230461114-0ac4dc71-7900-442e-a4e9-2ae1d6faecd3.png)
