### ISSUE TITLE
error in log with template sensor

### ISSUE THREAD

**Issue by jes1417** [gadgetchnnel/entities_calendar#2]
I have a template sensor I use to pull an attribute from a binary sensor to display in lovelace. I was trying to use this integration to add the sensor to my calendar but I am getting an error in the logs.

template sensor: 
```  
- platform: template
    sensors:
      dollars_food:
        friendly_name: Dollar Fed
        icon_template: mdi:dog
        device_class: timestamp
        value_template: >
          {% set t = state_attr('binary_sensor.wyzesense_dollars', 'timestamp') %}
          {% set u = as_timestamp(strptime(t,'%Y-%m-%dT%h:%m:%s')) %}
          {{ u | timestamp_custom("%-I:%M%p %m-%d-%Y") }}
```

which displays as:
![image](https://user-images.githubusercontent.com/38092747/83840673-cbba3380-a6c4-11ea-82fa-46ac67a0fba9.png)
![image](https://user-images.githubusercontent.com/38092747/83840945-687cd100-a6c5-11ea-9f53-20358ffabd05.png)

but when I add the sensor to my config using:

```calendar:
  - platform: entities_calendar
    calendars:
      - name: Pet Feedings
        entities:
          - entity: sensor.dollars_food
          - entity: sensor.bennys_food
```

I get this error:

```Log Details (ERROR)
Logger: homeassistant.helpers.entity
Source: custom_components/entities_calendar/calendar.py:251
First occurred: 12:33:06 AM (1 occurrences)
Last logged: 12:33:06 AM

Update for calendar.pet_feedings fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 168, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 251, in update
    "date": start.strftime('%Y-%m-%d'),
AttributeError: 'NoneType' object has no attribute 'strftime'
```

**Comment by gadgetchnnel** [comment]
That is not a valid datetime format for the "timestamp" device_class. If you use it in a regular Entities card, does it show "invalid date"?

The correct format for timestamps is the ISO format, like YYYY-MM-DDTHH:MM:SS*timezone* so I use something like `timestamp_custom("%Y-%m-%dT%H:%M:%S%z")` or, if you know the time is in UTC, `timestamp_custom("%Y-%m-%dT%H:%M:%SZ")`

If you want to still have the state in that format, you could add an attribute to your template sensor and use that with the new options added to Entities Calendar in the latest release.

Your sensor would look something like:

```
- platform: template
    sensors:
      dollars_food:
        friendly_name: Dollar Fed
        icon_template: mdi:dog
        device_class: timestamp
        value_template: >
          {% set t = state_attr('binary_sensor.wyzesense_dollars', 'timestamp') %}
          {% set u = as_timestamp(strptime(t,'%Y-%m-%dT%h:%m:%s')) %}
          {{ u | timestamp_custom("%-I:%M%p %m-%d-%Y") }}
        attribute_templates:
            iso_timestamp:
              {% set t = state_attr('binary_sensor.wyzesense_dollars', 'timestamp') %}
              {% set u = as_timestamp(strptime(t,'%Y-%m-%dT%h:%m:%s')) %}
              {{ u | timestamp_custom("%Y-%m-%dT%H:%M:%S%z") }}
```
and the Entities Calendar config like:

```
- platform: entities_calendar
    calendars:
      - name: Pet Feedings
        entities:
          - entity: sensor.dollars_food
             start_time:
               timestamp_attribute: iso_timestamp
             end_time:
               timestamp_attribute: iso_timestamp
```

**Comment by jes1417** [comment]
Thank you, that worked!

you are correct the sensor gave invalid date in the entities card.
 
The format in the examples was a little off but I got it fixed and it is working as expected,

```
  - platform: template
    sensors:
      dollars_food:
        friendly_name: Dollar Fed
        icon_template: mdi:dog
        device_class: timestamp
        value_template: >
          {% set t = state_attr('binary_sensor.wyzesense_dollars', 'timestamp') %}
          {% set u = as_timestamp(strptime(t,'%Y-%m-%dT%h:%m:%s')) %}
          {{ u | timestamp_custom("%-I:%M%p %m-%d-%Y") }}
        attribute_templates:
            iso_timestamp: >
              {% set t = state_attr('binary_sensor.wyzesense_dollars', 'timestamp') %}
              {% set u = as_timestamp(strptime(t,'%Y-%m-%dT%h:%m:%s')) %}
              {{ u | timestamp_custom("%Y-%m-%dT%H:%M:%S%z") }}

  - platform: template
    sensors:
      bennys_food:
        friendly_name: Benny Fed
        icon_template: mdi:cat
        device_class: timestamp
        value_template: >
          {% set t = state_attr('binary_sensor.wyzesense_bennys', 'timestamp') %}
          {% set u = as_timestamp(strptime(t,'%Y-%m-%dT%h:%m:%s')) %}
          {{ u | timestamp_custom("%-I:%M%p %m-%d-%Y") }}
        attribute_templates:
            iso_timestamp: >
              {% set t = state_attr('binary_sensor.wyzesense_bennys', 'timestamp') %}
              {% set u = as_timestamp(strptime(t,'%Y-%m-%dT%h:%m:%s')) %}
              {{ u | timestamp_custom("%Y-%m-%dT%H:%M:%S%z") }}
```

```
calendar:
  - platform: entities_calendar
    calendars:
      - name: Pet Feedings
        entities:
          - entity: sensor.dollars_food
            name: Dollar Fed
            start_time:
              timestamp_attribute: iso_timestamp
            end_time:
              timestamp_attribute: iso_timestamp
          - entity: sensor.bennys_food
            name: Benny Fed
            start_time:
              timestamp_attribute: iso_timestamp
            end_time:
              timestamp_attribute: iso_timestamp
```

shows:
![image](https://user-images.githubusercontent.com/38092747/83882608-fbd6f600-a707-11ea-86a2-bcb1a09be994.png)

it doesnt show in HACS Calendar Card:
![image](https://user-images.githubusercontent.com/38092747/83882841-46f10900-a708-11ea-816d-5369db65b821.png)

but that is ok.

thanks again for your help!
